name: Build and Upload Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install PlatformIO
      run: pip install platformio

    - name: Build PlatformIO project
      run: pio run --target buildrelease

    - name: Upload Release Assets
      run: |
        gh release upload ${{ github.ref }} firmware.bin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
